### ISSUE TITLE
训练时的损失只使用了多尺度的alpha L1 loss吗？

### ISSUE THREAD

**Issue by shuaige-inthewind** [kfeng123/LSA-Matting#2]
看到代码中只使用了alpha l1 loss。请问是使用composition loss和梯度损失效果不好吗？这两个loss是否有效？

**Comment by kfeng123** [comment]
您好，在我们做过的实验里，并没有观察到composition loss具有显著的效果提升。但我们注意到最近有些工作专门做matting里的composition, 比如[deep image composition](https://arxiv.org/abs/2011.02146)，不知道相关技巧是否会有帮助。

梯度损失这个我们没有做过相对系统的实验，所以并不确定。

另外我们还曾尝试过alpha l2 loss，在合适的学习率下，l2 loss也可以具有较好的效果。我个人的直观感觉是，l1 loss整体效果更好，l2 loss的局部效果更好。

希望这些经验能对你有帮助。

**Comment by shuaige-inthewind** [comment]
十分感谢
