### ISSUE TITLE
在测试的时候出现了问题，望回复！

### ISSUE THREAD

**Issue by BaiZS** [kfeng123/LSA-Matting#3]
您好，
    我刚刚接触图像抠图方面的内容，对您做出的东西非常感兴趣，也非常喜欢您的项目，我认为您的说明文档好精细啊！太负责了！但是我在复现的时候出现了一点小问题，不知道如何解决，这已经困扰我好久了，希望您能告知我解决办法！万分感谢！
![2022-05-29 15-53-10 的屏幕截图](https://user-images.githubusercontent.com/88708565/170858794-ed1bf73d-f855-4685-971d-6a946d21af0b.png)

**Comment by kfeng123** [comment]
您好，
这个错误是因为trimap_path这个路径不存在。请检查一下是否已经把trimap放在了这个路径下。

**Comment by BaiZS** [comment]
感谢感谢，万分感谢 0.o    
我以为是“not in model_dict” 的问题，一看那么多感叹号，怪吓人的，以为权重初始化弄错了，原来是数据集的问题，现已解决。
再次拜谢，好喜欢你的readme风格，细！
