### ISSUE TITLE
实验结果出现了一些问题，麻烦解惑！

### ISSUE THREAD

**Issue by BaiZS** [kfeng123/LSA-Matting#4]
您好，首先感谢您的项目，我觉得很厉害！
我用您的源代码复现了一遍，但是发现结果不尽人意，源代码我都没有改过，但是不管是用我自己训练出的模型跑测试得出的结果还是用您给的100轮模型跑出的结果，表现都不是很好，能看一下您跑的结果是什么样的吗，为什么我用您提供的模型跑的都表现不好？下面是几张最终结果图。
![16452523375_08591714cf_o](https://user-images.githubusercontent.com/88708565/183275916-5c360df6-eb99-4826-9ca0-2960cb726b19.png)
![Uploading antique-honiton-lace-1182740_1920.png…]()
![Uploading ball-597523_1920.png…]()

**Comment by kfeng123** [comment]
您好，用我们的100轮模型，在测试图片上跑出来的结果并不应该是这样的，应该是和ground truth很接近的。自己训练应该也是一样。这种结果很可能是出了bug了。您是用我们提供的测试代码进行测试的吗？代码做了哪些更改？

**Comment by BaiZS** [comment]
我是用的您发布的代码，我又重新测试了一次，步骤如下：

1.matting/utils/config.py中改数据集路径名称：
train_path_base = "/home/bai/Datasets/LSA_Dataset/AdobeTrain"；
“fg”文件夹中放的是原图像；
“kappa_fg”文件夹中放的是通过算法获得重新估计的前景，即运行"python tools/reestimate_foreground_final.py"得到的前景；
“coco_bg”中放的是"COCO_train2014_000000000009"等COCO数据集的图片；
“alpha”中放的是GroundTruth。
test_path_base = "/home/bai/Datasets/LSA_Dataset/AdobeTest"；
"merged"文件夹中放的是原Composition-1K数据集测试集中的50张原图片；
"trimaps"文件夹中放的是trimap图；
"alpha_copy"文件夹中放的是GroundTruth。
2.下载预训练模型resnetv1d50_b32x8_imagenet_20210531-db14775a.pth放在pretrained里面；下载最好的训练模型ckpt_e100.pth放在model里面；
3.测试时更改“matting/models/model.py”中的第105行：“for the_step in range(100):”改为“for the_step in range(1):”
4.运行bash test.sh

结果不尽人意，还是之前那样与GroundTruth相差甚远，不知哪里出现问题，希望您能帮忙看一下，万分感谢！

**Comment by BaiZS** [comment]
运行结果是这样的：
![1](https://user-images.githubusercontent.com/88708565/183569810-d93c5a05-11d9-4b20-b3f9-f8d1e5216730.jpg)
![2](https://user-images.githubusercontent.com/88708565/183569846-9b2d8ac6-d5a4-4369-8c59-9b3e0380128c.jpg)
![3](https://user-images.githubusercontent.com/88708565/183569861-612ded2d-dbaa-4b22-a726-34c07aaa5ffb.jpg)
![4](https://user-images.githubusercontent.com/88708565/183569874-282f064e-8774-48c6-9bc6-49542412594e.jpg)

**Comment by BaiZS** [comment]
如上所述，我复现的您的代码，修改的部分只有上述那几个，不知道哪里出问题了，结果很差，希望您能指导一下，麻烦帮忙看看是哪一步的问题？

**Comment by kfeng123** [comment]
> 如上所述，我复现的您的代码，修改的部分只有上述那几个，不知道哪里出问题了，结果很差，希望您能指导一下，麻烦帮忙看看是哪一步的问题？

您好，抱歉我才看到您的回复，最近有点忙。我根据您的描述，对一点有疑问，就是您说"merged"文件夹中放的是原Composition-1K数据集测试集中的50张原图片。我想问下，您这里放的，是前景背景合成之后的图片，还是没有合成的纯前景呢？

**Comment by BaiZS** [comment]
还得是大佬啊，我测试集放错了，尴尬了，应该放50*20=1000张的测试图片是吗，也就是用的是GCA Matting的测试集？

**Comment by kfeng123** [comment]
> 还得是大佬啊，我测试集放错了，尴尬了，应该放50*20=1000张的测试图片是吗，也就是用的是GCA Matting的测试集？

嗯放1000张，adobe有自己合成的代码，印象中gca的合成的代码和adobe官方的有点差别。

我们的模型应该不会有什么大问题。我们花了功夫做的。它真的有效，没有水分。

**Comment by BaiZS** [comment]
是，我很喜欢您的项目，不然也不会断断续续搞了一个多月了，希望能从您这学习到东西，我目前也是刚接触这方面，有很多东西都不太会，给您添麻烦了，也感谢您的回复，望您学术顺利！
